name: "Setup JFrog CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: https://dhanushartifactory.devopsacc.team

          # JFrog Platform access token
          JF_ACCESS_TOKEN: eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJ3c3A5TTQyMWI0Ym1tX0l4am80bDRzSEQwTXdwMU5ZTFFWNy1QMERCRlJNIn0.eyJzdWIiOiJqZmFjQDAxamNxaGJqNDZhcHByMDhiN3RqNjEwaDE4L3VzZXJzL2FkbWluIiwic2NwIjoiYXBwbGllZC1wZXJtaXNzaW9ucy9hZG1pbiIsImF1ZCI6IipAKiIsImlzcyI6ImpmZmVAMDFqY3FoYmo0NmFwcHIwOGI3dGo2MTBoMTgiLCJpYXQiOjE3MzE3NjU0MDUsImp0aSI6IjRlNThiZDllLTI0YmYtNGQ1OC05YWZiLWE3NDM0ZmMyNTJkZCJ9.W1xG6enTYd6uyTkMsDfByjcug_EZyzGUfO_05kyuqTwA0QwCV4VKLZLQLrktyKp84r85_jStM1ct-y2RmGnJvCqpEI5tFEYob_FfuFJy7h9ONJxDUNi4TVhcbPilvdDXhSTz2plJHMI_8wHXB859NfrhXhSojz5q6dZ4nGc030fl6QjH_msfnEakq-Nbm19XsQSHfDtXGHjMYv_9tTcoL5FFwz7RNddg7qepA5wIRiyr2_K25CYRV-1HK_zbS176Ha2Nd2cr4JNjIkXt2YkvIIh_5STCXWn1FtUqsnjoN8yXEXhWFJODMDTNO1B0yNu_tR5x1frbPBxE67XEB3uvBA

      - name: Run JFrog CLI
        run: |
          # Ping the server
          jf rt ping
          # Collect environment variables for the build
          jf rt bce
          # Collect VCS details from git and add them to the build
          jf rt bag
          # Publish build info
          jf rt bp
