name: "BMW-GithubActions-Example"

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform URL
          JF_URL: https://dhanushvm07.jfrog.io/
          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Run JFrog CLI
        run: 
          # Ping the server
          jf rt ping
      - name: Run JFrog CLI
        run:
          # Configure Maven project's repositories
          jf mvnc --repo-resolve-releases bmw-test-01-libs-release \
                  --repo-resolve-snapshots bmw-test-01-libs-snapshot \
                  --repo-deploy-releases bmw-test-01-libs-release \
                  --repo-deploy-snapshots bmw-test-01-libs-snapshot
      - name: Mvn Clean install
          jf mvn install -DskipTests
          # Scan for SCA
          # jf audit
