name: "Maven Build using JFrog Platform"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptium'  # Corrected distribution

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform URL
          JF_URL: https://dhanushartifactory.devopsacc.team

          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Run JFrog CLI
        run: |
          # Ping the server
          jf rt ping
          # Configure Maven project's repositories
          jf mvnc --repo-resolve-releases dhanush-github-libs-release --repo-resolve-snapshots dhanush-github-libs-snapshots
          # Install and publish project
          jf mvn clean install -DskipTests
