name: "BMW-GithubActions-Example"

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://dhanushvm07.jfrog.io/
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Run JFrog CLI Ping
        run: jf rt ping

      - name: Configure Maven repositories in JFrog CLI
        run: |
          jf mvnc --repo-resolve-releases bmw-test-01-libs-release \
                  --repo-resolve-snapshots bmw-test-01-libs-snapshot \
                  --repo-deploy-releases bmw-test-01-libs-release \
                  --repo-deploy-snapshots bmw-test-01-libs-snapshot

      - name: Build and Install Maven Project
        run: jf mvn install -DskipTests

      - name: Scan for SCA (Optional)
        run: jf audit
